name: 'Publish website to Github Pages'

on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/setup-env
      - name: Ruff
        run: uv run ruff check src/

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/setup-env
      - name: MyPy
        run: uv run mypy src/
  
  pytest:
    runs-on: ubuntu-latest
    needs:
      - ruff
      - mypy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/setup-env
      - name: PyTest
        run: |
          uv run pytest --cov=src --cov-report=json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
  publish:
    runs-on: ubuntu-latest
    needs:
      - pytest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/workflows/composite/setup-env    
      - name: Create page content
        run: |
          cd src
          uv run pelican content -s core/settings.py -o ~/public
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ~/public
